version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: droxstock_app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
    networks:
      - droxstock_network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: droxstock_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - droxstock_network
    depends_on:
      - app

  redis:
    image: redis:7-alpine
    container_name: droxstock_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - droxstock_redis_data:/data
    networks:
      - droxstock_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  queue:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: droxstock_queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./:/var/www/html
    networks:
      - droxstock_network
    depends_on:
      - redis

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: droxstock_scheduler
    restart: unless-stopped
    command: /bin/sh -c "while [ true ]; do php artisan schedule:run --verbose --no-interaction & sleep 60; done"
    volumes:
      - ./:/var/www/html
    networks:
      - droxstock_network
    depends_on:
      - redis

networks:
  droxstock_network:
    driver: bridge

volumes:
  droxstock_redis_data:
    driver: local
